In [2]:
import numpy as np

In [3]:
array=np.array([[1,1,4,5,1,4],
                [1,9,1,9,8,1]])
print(array[array>1])
array[array>1]=10
print(array)

[4 5 4 9 9 8]
[[ 1  1 10 10  1 10]
 [ 1 10  1 10 10  1]]


In [4]:
mines_array=np.random.choice(25,size=5,replace=False)
print(mines_array)

[ 0 15  9  2 12]
